import { View, ScrollView } from "react-native";
import { useLocalSearchParams, useRouter } from "expo-router";
import Head from "expo-router/head";
import { useQuery } from "@tanstack/react-query";
import { api } from "../../src/services/client";
import { usePlayer } from "../../src/player/store";
import { Screen } from "../../src/components/Screen";
import { Display, Heading, Body, Card, Button, Badge, CoverArt } from "../../src/components/ui";
import { rands, duration } from "../../src/theme";

export default function TrackDetail() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const router = useRouter();
  const play = usePlayer((s) => s.play);

  const trackQ = useQuery({ queryKey: ["track", id], queryFn: () => api.getTrack(String(id)) });
  const track = trackQ.data;

  if (!track) {
    return (
      <Screen>
        <Body className="mt-8 text-center">{trackQ.isLoading ? "Loading…" : "Track not found."}</Body>
      </Screen>
    );
  }

  const seo = api.seo(track);

  return (
    <Screen>
      {/* AEO: structured metadata for the web export's <head>. No-op on native. */}
      <Head>
        <title>{`${track.title} — ${track.artistName} | Umhlabatea`}</title>
        <meta name="description" content={seo.description} />
        <meta name="keywords" content={seo.keywords.join(", ")} />
        <meta property="og:title" content={`${track.title} — ${track.artistName}`} />
        <meta property="og:description" content={seo.description} />
        <meta property="og:type" content="music.song" />
        <script type="application/ld+json">{JSON.stringify(seo.jsonLd)}</script>
      </Head>

      <View className="mb-4 mt-2 flex-row items-center gap-4">
        <CoverArt seed={track.id} size={96} rounded="rounded-2xl" label={track.title} />
        <View className="flex-1">
          <Display className="text-3xl text-earth-dark">{track.title}</Display>
          <Body className="text-earth-brown">{track.artistName}</Body>
          <View className="mt-2 flex-row flex-wrap gap-2">
            <Badge label={track.genre} tone="primary" />
            <Badge label={`${track.bpm} BPM`} tone="sage" />
            <Badge label={track.key} tone="muted" />
            {track.generated ? <Badge label="AI-generated" tone="accent" /> : null}
          </View>
        </View>
      </View>

      <View className="mb-4 flex-row gap-3">
        <View className="flex-1">
          <Button label="▶  Play" onPress={() => play(track)} />
        </View>
        <View className="flex-1">
          <Button label={`Buy ${rands(track.priceRands)}`} variant="dark" onPress={() => router.push("/subscriptions")} />
        </View>
      </View>

      <Card className="mb-4">
        <Heading className="mb-1 text-xl">Duration</Heading>
        <Body>{duration(track.durationSec)} · {track.progression || "—"}</Body>
      </Card>

      <Heading className="mb-2 mt-2 text-2xl">SEO / AEO Optimization</Heading>
      <Body className="mb-3 text-sm">Auto-generated by the discovery agent so this track is found by search engines and AI assistants.</Body>

      <Card className="mb-3">
        <Body className="text-xs uppercase tracking-wide">Meta description</Body>
        <Body className="mt-1 text-earth-dark">{seo.description}</Body>
      </Card>

      <Card className="mb-3">
        <Body className="mb-2 text-xs uppercase tracking-wide">Keywords</Body>
        <View className="flex-row flex-wrap gap-2">
          {seo.keywords.map((k) => (
            <Badge key={k} label={k} tone="muted" />
          ))}
        </View>
      </Card>

      <Card className="mb-3">
        <Body className="mb-2 text-xs uppercase tracking-wide">Answer-engine phrases</Body>
        {seo.voiceSearch.map((v) => (
          <Body key={v} className="text-earth-dark">“{v}”</Body>
        ))}
      </Card>

      <Button label="Register rights for this track →" variant="outline" onPress={() => router.push("/compliance")} />
    </Screen>
  );
}
